name: Codecov

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: codecov-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  codecov:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2 # To ensure we have enough history for code coverage

      - uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.12

      - name: Test with Python 3.12
        run: uv run --frozen pytest --cov --cov-branch --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
